### ISSUE TITLE
Input for design of new BC66 board?

### ISSUE THREAD

**Issue by Humancell** [Wiz-IO/Arduino-Quectel-BC66#10]
Hello,

I am designing a new board, based on the BC66-TE-B, that will be in a UNO or Feather form factor.  I want to do this and make it available to everyone working to create solutions using the BC66 and your work.

I am curious if you have any input on changes you would like to see in such a board?  If I am starting with the design of the BC66-TE-B, what do you think should be removed or added?

I already have my own ideas and have begun the work, however I wanted to get your input before we spun the first PCBs since you have more experience working with the BC66-TE-B and might know things your would change in a new design.

I look forward to any comments or input!

Thanks!

**Comment by Wiz-IO** [comment]
Hi,
Nice !

Maybe need only level-translators

**Comment by Wiz-IO** [comment]
[BC26-TE-B_SCH_V1.2_20171113.pdf](https://github.com/Wiz-IO/Arduino-Quectel-BC66/files/3693564/BC26-TE-B_SCH_V1.2_20171113.pdf)
