### ISSUE TITLE
BC66 to push GPS data to Firebase

### ISSUE THREAD

**Issue by rajendran20** [Wiz-IO/Arduino-Quectel-BC66#11]
Hi, 

Does anyone know how to post data (GPS) to google firebase database using BC66 module. Using AT commands. Can we use MQTT?

**Comment by Wiz-IO** [comment]
SSL for NarrowBand is bad solution

**Comment by rajendran20** [comment]
Any suggestions?

**Comment by Wiz-IO** [comment]
https://forums.quectel.com/t/posting-to-firebase-database-from-bc66/2759/4
or
https://www.quectel.com/support/contact.htm
