### ISSUE TITLE
Compiling in Arduino IDE

### ISSUE THREAD

**Issue by CrabbyPete** [Wiz-IO/Arduino-Quectel-BC66#13]
Does this compile with the Arduino IDE. I am trying to compile info.c and I get
C:\Users\Peter\Projects\Arduino-Quectel-BC66\examples\info\info.ino: In function 'void setup()':

info:15:3: error: 'Dev' was not declared in this scope

   Dev.noSleep(); // disable PSM sleep

   ^

info:18:10: error: 'class Serial_' has no member named 'debug'

   Serial.debug(); // enable debug for this port, DBG( work as printf )

          ^

info:20:10: error: 'class Serial_' has no member named 'printf'

   Serial.printf("Arduino      %s\n", Dev.getVersion());

          ^

info:22:10: error: 'class Serial_' has no member named 'printf'

   Serial.printf("IMEI         %s\n", imei.c_str());

          ^

info:24:10: error: 'class Serial_' has no member named 'printf'

   Serial.printf("UID          %s\n", uid.c_str());

          ^

info:29:10: error: 'class Serial_' has no member named 'printf'

   Serial.printf("MCCMNC       %s\n", mcc_mnc.c_str());

          ^

info:31:10: error: 'class Serial_' has no member named 'printf'

   Serial.printf("IMSI         %s\n", sim_imsi.c_str());

          ^

info:33:10: error: 'class Serial_' has no member named 'printf'

   Serial.printf("ICCID        %s\n", sim_iccid.c_str());

          ^

info:38:10: error: 'class Serial_' has no member named 'printf'

   Serial.printf("Rx level     %d dbm\n", Dev.getReceiveLevel());

          ^

info:39:10: error: 'class Serial_' has no member named 'printf'

   Serial.printf("Rx quality   %d\n", Dev.getQuality());

          ^

info:40:10: error: 'class Serial_' has no member named 'printf'

   Serial.printf("Rx access    %d\n", Dev.getAccess());

          ^

info:41:10: error: 'class Serial_' has no member named 'printf'

   Serial.printf("Cell cid     %d\n", Dev.getCid());

          ^

info:42:10: error: 'class Serial_' has no member named 'printf'

   Serial.printf("Cell tac     %d\n", Dev.getTac());

          ^

info:45:10: error: 'class Serial_' has no member named 'printf'

   Serial.printf("Cell mlts    %s\n", mlts);

          ^

info:46:11: error: 'LED' was not declared in this scope

   pinMode(LED, OUTPUT);

           ^

info:48:10: error: 'class Serial_' has no member named 'printf'

   Serial.printf("Elapsed: %d mili seconds\n", millis() - t);

          ^

C:\Users\Peter\Projects\Arduino-Quectel-BC66\examples\info\info.ino: In function 'void loop()':

info:56:16: error: 'LED' was not declared in this scope

   digitalWrite(LED, ++led & 1);

                ^

exit status 1
'Dev' was not declared in this scope

**Comment by Wiz-IO** [comment]
is declared
https://github.com/Wiz-IO/Arduino-Quectel-BC66/blob/master/cores/opencpu/DEV.cpp#L293

try after
#include <Arduino.h>
#include <DEV.h>

**Comment by CrabbyPete** [comment]
All works great
