### ISSUE TITLE
Compiling In Arduino 1.8.10 ... is it supported?

### ISSUE THREAD

**Issue by alfredtyaga** [Wiz-IO/Arduino-Quectel-BC66#14]
This is compile log for a blank sketch, on fresh setup Win7x64, Arduino 1.8.10, and your core installed via board manager... Any suggestions?

Using built-in specs.

COLLECT_GCC=C:\Users\user\AppData\Local\Arduino15\packages\WizIO\tools\bc66_gcc\1.70201.0\bin\arm-none-eabi-g++

COLLECT_LTO_WRAPPER=c:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/lto-wrapper.exe

Target: arm-none-eabi

Configured with: /tmp/jenkins/jenkins-GCC-7-build_toolchain_docker-633_20171130_1512067137/src/gcc/configure --build=x86_64-linux-gnu --host=i686-w64-mingw32 --target=arm-none-eabi --prefix=/tmp/jenkins/jenkins-GCC-7-build_toolchain_docker-633_20171130_1512067137/install-mingw --libexecdir=/tmp/jenkins/jenkins-GCC-7-build_toolchain_docker-633_20171130_1512067137/install-mingw/lib --infodir=/tmp/jenkins/jenkins-GCC-7-build_toolchain_docker-633_20171130_1512067137/install-mingw/share/doc/gcc-arm-none-eabi/info --mandir=/tmp/jenkins/jenkins-GCC-7-build_toolchain_docker-633_20171130_1512067137/install-mingw/share/doc/gcc-arm-none-eabi/man --htmldir=/tmp/jenkins/jenkins-GCC-7-build_toolchain_docker-633_20171130_1512067137/install-mingw/share/doc/gcc-arm-none-eabi/html --pdfdir=/tmp/jenkins/jenkins-GCC-7-build_toolchain_docker-633_20171130_1512067137/install-mingw/share/doc/gcc-arm-none-eabi/pdf --enable-languages=c,c++ --enable-mingw-wildcard --disable-decimal-float --disable-libffi --disable-libgomp --disable-libmudflap --disable-libquadmath --disable-libssp --disable-libstdcxx-pch --disable-nls --disable-shared --disable-threads --disable-tls --with-gnu-as --with-gnu-ld --with-headers=yes --with-newlib --with-python-dir=share/gcc-arm-none-eabi --with-sysroot=/tmp/jenkins/jenkins-GCC-7-build_toolchain_docker-633_20171130_1512067137/install-mingw/arm-none-eabi --with-libiconv-prefix=/tmp/jenkins/jenkins-GCC-7-build_toolchain_docker-633_20171130_1512067137/build-mingw/host-libs/usr --with-gmp=/tmp/jenkins/jenkins-GCC-7-build_toolchain_docker-633_20171130_1512067137/build-mingw/host-libs/usr --with-mpfr=/tmp/jenkins/jenkins-GCC-7-build_toolchain_docker-633_20171130_1512067137/build-mingw/host-libs/usr --with-mpc=/tmp/jenkins/jenkins-GCC-7-build_toolchain_docker-633_20171130_1512067137/build-mingw/host-libs/usr --with-isl=/tmp/jenkins/jenkins-GCC-7-build_toolchain_docker-633_20171130_1512067137/build-mingw/host-libs/usr --with-libelf=/tmp/jenkins/jenkins-GCC-7-build_toolchain_docker-633_20171130_1512067137/build-mingw/host-libs/usr --with-host-libstdcxx='-static-libgcc -Wl,-Bstatic,-lstdc++,-Bdynamic -lm' --with-pkgversion='GNU Tools for Arm Embedded Processors 7-2017-q4-major' --with-multilib-list=rmprofile

Thread model: single

gcc version 7.2.1 20170904 (release) [ARM/embedded-7-branch revision 255204] (GNU Tools for Arm Embedded Processors 7-2017-q4-major) 

COMPILER_PATH=c:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/;c:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../lib/gcc/;c:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/bin/

LIBRARY_PATH=c:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/thumb/v7e-m/fpv4-sp/hard/;c:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/hard/;c:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/hard/;c:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/;c:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../lib/gcc/;c:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/lib/;c:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../arm-none-eabi/lib/

COLLECT_GCC_OPTIONS='-mcpu=cortex-m4' '-mfloat-abi=hard' '-mfpu=fpv4-sp-d16' '-fsingle-precision-constant' '-mlittle-endian' '-mthumb' '-mthumb-interwork' '-nostartfiles' '-nodefaultlibs' '-fno-use-cxa-atexit' '-T' 'C:\Users\user\AppData\Local\Arduino15\packages\WizIO\hardware\bc66\2.0.0\cores\opencpu/cpp_bc66.ld' '-o' 'C:\Users\user\AppData\Local\Temp\arduino_build_402585/sketch_dec10a.ino.elf' '-LC:\Users\user\AppData\Local\Temp\arduino_build_402585' '-v'

 c:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/collect2.exe -plugin c:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/liblto_plugin-0.dll -plugin-opt=c:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/lto-wrapper.exe -plugin-opt=-fresolution=C:\Users\user\AppData\Local\Temp\ccFHlrjV.res --sysroot=c:\users\user\appdata\local\arduino15\packages\wizio\tools\bc66_gcc\1.70201.0\bin\../arm-none-eabi -EL -X -o C:\Users\user\AppData\Local\Temp\arduino_build_402585/sketch_dec10a.ino.elf -LC:\Users\user\AppData\Local\Temp\arduino_build_402585 -Lc:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/thumb/v7e-m/fpv4-sp/hard -Lc:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/hard -Lc:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/hard -Lc:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1 -Lc:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../lib/gcc -Lc:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/lib -Lc:/users/user/appdata/local/arduino15/packages/wizio/tools/bc66_gcc/1.70201.0/bin/../arm-none-eabi/lib --gc-sections --gc-sections --start-group C:\Users\user\AppData\Local\Temp\arduino_build_402585/core\core.a sketch\sketch_dec10a.ino.cpp.o core\variant_pins.c.o core\variant.cpp.o C:\Users\user\AppData\Local\Arduino15\packages\WizIO\hardware\bc66\2.0.0\cores\opencpu/lib_app_start_bc66.a C:\Users\user\AppData\Local\Arduino15\packages\WizIO\hardware\bc66\2.0.0\cores\opencpu/lib_BC66R01A04V01.a --end-group -T C:\Users\user\AppData\Local\Arduino15\packages\WizIO\hardware\bc66\2.0.0\cores\opencpu/cpp_bc66.ld

COLLECT_GCC_OPTIONS='-mcpu=cortex-m4' '-mfloat-abi=hard' '-mfpu=fpv4-sp-d16' '-fsingle-precision-constant' '-mlittle-endian' '-mthumb' '-mthumb-interwork' '-nostartfiles' '-nodefaultlibs' '-fno-use-cxa-atexit' '-T' 'C:\Users\user\AppData\Local\Arduino15\packages\WizIO\hardware\bc66\2.0.0\cores\opencpu/cpp_bc66.ld' '-o' 'C:\Users\user\AppData\Local\Temp\arduino_build_402585/sketch_dec10a.ino.elf' '-LC:\Users\user\AppData\Local\Temp\arduino_build_402585' '-v'

exit status -1
Error compiling for board Quectel BC66 Module.

**Comment by Wiz-IO** [comment]
seem as Arduino Admin Rights issue

**Comment by alfredtyaga** [comment]
Yes, Run As Administrator fixes that issue.
However its strange that some other third party cores and previous Arduino releases are working flawless without administrator rights.
Thank you very much for the hint!

**Comment by Wiz-IO** [comment]
try this
https://github.com/Wiz-IO/platform-quectel
