### ISSUE TITLE
bc66_tools is not available for MacOS or Linux

### ISSUE THREAD

**Issue by spit4520** [Wiz-IO/Arduino-Quectel-BC66#15]
Hello,

What modifications need to be made in order for you to accept a pull request to allow me to run the tools in the Arduino IDE on Linux/MacOS? I don't use windows and would prefer not to.

Best Regards,

Scott

**Comment by Wiz-IO** [comment]
this must work 
https://github.com/Wiz-IO/platform-quectel

or use this script
https://github.com/Wiz-IO/platform-quectel/blob/master/builder/frameworks/MT2625.py

**Comment by spit4520** [comment]
Issue Resolved Thank you, Please see new issue for next bug
