### ISSUE TITLE
Iot flash tool Error: Failed to parse config file

### ISSUE THREAD

**Issue by ASL07** [Wiz-IO/Arduino-Quectel-BC66#18]
Hi Georgi

I have downloaded flash tool from https://app.box.com/s/3wrkh1yzn09yuyb5f8v5vllmlir0571s
When I launch FlashTool.exe I get the following error:

![image](https://user-images.githubusercontent.com/4049435/75440272-c4fc8180-595b-11ea-97bf-85c337ba9c21.png)

I am not able to locate the config file, could you let me know where to get it?

Thanks

**Comment by Wiz-IO** [comment]
Hi
Just ask firmware from your local Quectel support
I'm not authorized to share Quectel firmwares

**Comment by nestorayuso** [comment]
unzip Firmware_BC66NBR01A04V01.zip or the firmware you are using

**Comment by ASL07** [comment]
@nestorayuso 
Thanks for the info, I thought that zip just contained the bin file

I am getting a different error now, using the configuration file:
![image](https://user-images.githubusercontent.com/4049435/75446617-0561fc80-5968-11ea-902b-b35051755aca.png)

But the driver is correctly installed and the board recognized as a com port

I got the ch340 driver from here https://learn.sparkfun.com/tutorials/how-to-install-ch340-drivers/all (the one provided on https://app.box.com/s/3wrkh1yzn09yuyb5f8v5vllmlir0571s didn't work)

**Comment by Wiz-IO** [comment]
Olimex?
so... run updater and click board button ON or RST
**only PIO have auto** buttons click function

**Comment by ASL07** [comment]
Yes, it worked now. Thanks @Wiz-IO 

I have just restored AT functionality using Solution 1 https://github.com/Wiz-IO/platform-quectel/wiki/Framework-OpenCPU

Should I be able to send AT commands through the USB port now?

I have tried to send AT commands using both USB port, RX/TX pins and Aux RX/TX at 115200 and 9600 bauds and I got no response from the modem whatsoever.

**Comment by Wiz-IO** [comment]
Best "AT" restore... just flash module with firmware 10

**Comment by ASL07** [comment]
I was able to restore it using this tool https://github.com/OLIMEX/NB-IoT

**Comment by Wiz-IO** [comment]
after restore AT must exist over USB/UART
