### ISSUE TITLE
Code uploaded but not running

### ISSUE THREAD

**Issue by mightChamp** [Wiz-IO/Arduino-Quectel-BC66#19]
I am testing BC66-TE-B-KIT without SIM. Just want some data print on serial for now.
I uploaded BC66NBR01A04V01 firmware to  BC66-TE-B-KIT, then 
I uploaded code successfully to BC66-TE-B-KIT.
After code upload not getting any prints on serial port.

When I press PWR_KEY I got this :

F1: 0000 0000
V0: 0000 0000 [0001]
00: 0006 000C
01: 0000 0000
U0: 0000 0001 [0000]
T0: 0000 00B4
Leaving the BROM

After that nothing happens.

**Comment by Wiz-IO** [comment]
select from Arduino IDE  Tools - drop-down menu ... module firmware, then compile and upload

**Comment by mightChamp** [comment]
I have uploaded my code  with BC66NBR01A04V01 selected and complied from Arduino IDE already, but I didn't get any output on serial port.
Then I tries PlatfromIO for this task. Code compiled but I am unable to upload code to it.
I got error in uploading:

ERROR: EPP Answer
*** [upload] Explicit exit, status 2
============================= [FAILED] Took 3.55 seconds ============== The terminal process terminated with exit code: 1

**Comment by Wiz-IO** [comment]
on boot

- if module is OFF, click button ON
- if module is ON, click button RST

**Comment by mightChamp** [comment]
There is only PWR_KEY,RESET and PSM_ENT push button on this kit.
How to know module is OFF, and which is button ON?

There is two LED for indication one is NET_LIGHT and second one is PSM_IND.
On Start PSM_IND is on and NET_LIGHT is off. 
and when to upload code by pressing PWR_KEY NET_LIGHT becomes on and after code upload done this becomes off
[https://cdn.shopify.com/s/files/1/0067/0249/7890/products/bc66dev-kit_600x_crop_center.png?v=1571108375](url)

**Comment by Wiz-IO** [comment]
https://fmgelectronics.ie/wp-content/uploads/2019/10/BC66-DVK-Quectel-BC66-Development-Board.jpg

???

**Comment by mightChamp** [comment]
> There is only PWR_KEY,RESET and PSM_ENT push button on this kit.
> How to know module is OFF, and which is button ON?
> 
> There is two LED for indication one is NET_LIGHT and second one is PSM_IND.
> On Start PSM_IND is on and NET_LIGHT is off.
> and when to upload code by pressing PWR_KEY NET_LIGHT becomes on and after code upload done this becomes off
> [https://cdn.shopify.com/s/files/1/0067/0249/7890/products/bc66dev-kit_600x_crop_center.png?v=1571108375](url)

I updated it please look for it.

**Comment by mightChamp** [comment]
![image](https://user-images.githubusercontent.com/45094530/77052457-daad1600-69f2-11ea-8bff-0fe3956ead57.png)

**Comment by Wiz-IO** [comment]
![bc66dev-kit_600x_crop_center](https://user-images.githubusercontent.com/14574834/77052682-dfaf9c80-69d5-11ea-8016-d70d69abd09b.png)

**Comment by Wiz-IO** [comment]
are you sure that firmware is BC66NBR01A04V01?

**Comment by mightChamp** [comment]
I think am sure I use this link [https://app.box.com/s/3wrkh1yzn09yuyb5f8v5vllmlir0571s](url)  to download firmware.

**Comment by Wiz-IO** [comment]
with this firmware I work one year

**Comment by mightChamp** [comment]
From Iot Flash Flash Tool selected flash_download.cfg files before This I taken backup of nvdm.
Then I click Start and pressed PWR_KEY and Firmware uploaded to it. Then I uploaded Code from Arduino IDE.

**Comment by mightChamp** [comment]
> with this firmware I work one year

Thats's sound great.
Could you think this as a Hardware Side Issue?
As there are many jumpers on board and have to select them proper to make it work?

**Comment by Wiz-IO** [comment]
if IoT tool work the jumper is OK
are you sure that your module is BC66**NB**-04-STD

**Comment by mightChamp** [comment]
Yes module is BC66NB-04-STD it is mentioned on module.
Is SIM card is necessary for module? can I test without it?

**Comment by Wiz-IO** [comment]
no idea ... must work fine
or wrong application code

**Comment by Wiz-IO** [comment]
yes, work without SIM

**Comment by mightChamp** [comment]
can you be sure that this code will works:

`void setup(){
 Serial.begin(115200);
Serial.println("Hello");
}
void loop(){
}
`

I also tried printing in loop() but didn't work.

**Comment by Wiz-IO** [comment]
yep, this serial use usb-com as IoT Tool

**Comment by Wiz-IO** [comment]
https://github.com/Wiz-IO/Arduino-Quectel-BC66/blob/master/examples/info/info.ino#L62

**Comment by mightChamp** [comment]
usb-com means USB_DEBUG microusb port?
When I connect board I get 4 COM ports. I use interference 0 (COM31 on my PC) for code upload.

**Comment by Wiz-IO** [comment]
![20200319_120557](https://user-images.githubusercontent.com/14574834/77055853-459e2300-69da-11ea-97ef-5ffe2f351e9a.jpg)

**Comment by Wiz-IO** [comment]
btw: Arduino IDE not support version 10

if you want to use v10 use PlatformIO port

**Comment by mightChamp** [comment]
> btw: Arduino IDE not support version 10
> 
> if you want to use v10 use PlatformIO port

Sorry but I din't get v10? Which is about v10

**Comment by mightChamp** [comment]
> btw: Arduino IDE not support version 10
> 
> if you want to use v10 use PlatformIO port

I tried platformIO also but I unable to upload code there? get this issue :
ERROR: EPP Answer
*** [upload] Explicit exit, status 2
============================= [FAILED] Took 3.55 seconds =============================
The terminal process terminated with exit code: 1

**Comment by Wiz-IO** [comment]
PIO not support v4 and 5
https://github.com/Wiz-IO/platform-quectel/wiki/SDK-BC66
