### ISSUE TITLE
No response from power on / reset button

### ISSUE THREAD

**Issue by OlineStaerke** [Wiz-IO/Arduino-Quectel-BC66#20]
Hi, 
I am having problems with the board. I set up the system as described, but when i press the power on / reset button I get no response. 
What could be the problem ? 

Thank you in advance.

**Comment by Wiz-IO** [comment]
Hi
what module, what firmware?

**Comment by Wiz-IO** [comment]
flash module with BC66NBR01A10 ( will remove old User Application )
then return firmware BC66NBR01A04 or BC66NBR01A05 ( if you use Arduino IDE, if PlatformIO v10 is ok )

or read this https://github.com/Wiz-IO/platform-quectel/wiki/Framework-OpenCPU#bc66-bc26-attention

or you have hardware problem
