### ISSUE TITLE
Support Linux hosts

### ISSUE THREAD

**Issue by probonopd** [Wiz-IO/Arduino-Quectel-BC66#3]
Please support Linux hosts.

What is missing? A way to upload from Linux instead of

```
## sketch uploader
tools.bc66_uploader.cmd=coda.exe
tools.bc66_uploader.cmd.windows=coda.exe
```

or are other things missing as well?

As for the uploader, possibly https://github.com/eret1k/SP-Flash-Tool-src or https://github.com/MediaTek-Labs/mt76x7-uploader can be used.

**Comment by Wiz-IO** [comment]
OK, next update... 
but coda.exe is for Windows(is Quectel software)
can you try somebody Linux uploader?

If you have other things for Linux, just write
I will try to make some PC with Ubunto for tests

**Comment by probonopd** [comment]
The module is from Quectel but the chipset is from Mediatek, hence I was assuming that Mediatek-compatible uploader code could possibly be used.

**Comment by Wiz-IO** [comment]
I know... I not have now Linux machine for tests

**Comment by Wiz-IO** [comment]
Linux 64 Coda
https://labs.mediatek.com/en/download/r7bcGqEW

Manual:
https://labs.mediatek.com/en/download/rmrArsWL

**Comment by Wiz-IO** [comment]
Hi, 
comming soon MT2625 Python uploader 
here will be:
https://github.com/Wiz-IO/tool-quectel

**Comment by Wiz-IO** [comment]
https://github.com/Wiz-IO/Mediatek-MT2625-Flash-Utility
