### ISSUE TITLE
Arduino BC66 shield

### ISSUE THREAD

**Issue by x893** [Wiz-IO/Arduino-Quectel-BC66#4]
Hello Georgi,
may be you can publish hardware files for Arduino BC66 shield ?
Thanks
Mitek

**Comment by Wiz-IO** [comment]
Hi Mitek,
About hardware, the best "choice" is contact Quectel Support ( I will ask them to share... )
https://www.quectel.com/support/contact.htm

or email me...

**Comment by x893** [comment]
Thanks, i ask local reseller also.
