### ISSUE TITLE
AT commands restoration

### ISSUE THREAD

**Issue by v8088** [Wiz-IO/Arduino-Quectel-BC66#5]
Hi,
I cannot restore the AT command support.
I made the NVDM backup as recommended before uploading any sketch, but even after NVDM restore the module still runs the sketch and I cannot get the AT commands back.
How to restore the AT commands?
The module is version BC66NBR01A04

**Comment by Wiz-IO** [comment]
Hi,
This issue is Quectel / OpenCpu issue....
I don`t known real solution,  some time this solution work...
I ask Quectel - how to? - still waiting ...

second solution - but is your risk - there is button format, then reflash firmware and restore NVDM
risk is - you may lose IMEI as zeroes ....

**Comment by Wiz-IO** [comment]
The solution:
https://github.com/Wiz-IO/platform-quectel/wiki/Framework-OpenCPU#how-to-restore-at-command-interface

**Comment by jaecktec** [comment]
Hey, I am currently also trying to restore my firmware, however I can't flash anything anymore. Probably thats my fault 🙈 however I was hoping you might already have faced this problem:

`Category: Tool Issue
Error Code: S_BROM_CMD_STARTCMD_TIMEOUT (2006)`

My module is labeled `BC66NBTEB-04-STD`

**Comment by Wiz-IO** [comment]
Hi
Which software you use... Try IoT_FlashTool
and look board Key USB/UART
If main uart is "OK" the module can not "die"

**Comment by jaecktec** [comment]
I am using the IoT_FlashTool v2.7.3 and I can see 4 UARTs connected in the device manager 
(USB to UART Bridge Inteface 0 to 3)
It used to work on Interface 0. 

![DSC_0404](https://user-images.githubusercontent.com/10283382/60992259-6b9ffd80-a34c-11e9-94cb-05f3aaad886d.JPG)

I guess you are reffering to the switch on the top left? For me the switch position doesn't make a difference :(

**Comment by Wiz-IO** [comment]
maybe hardware problem? ask Quectel...
