### ISSUE TITLE
Support for Quectel BG96 ...

### ISSUE THREAD

**Issue by Humancell** [Wiz-IO/Arduino-Quectel-BC66#7]
Hello,

This is a great project, and I appreciate all of your work!  I saw the video of you supporting the BG96, but did not find the documentation here.

https://www.youtube.com/watch?v=OjdAD0WR6vw

Can this be done from the Arduino IDE?  Or does it require other tools?  I am very interested in this, and would be interested in donating to your progress - and helping get more information from Quectel if necessary - to keep this moving forward!

**Comment by Wiz-IO** [comment]
is not ready yet ( PlatformIO ) - very soon... need to check  some periphery libraries
support ThreadX and Arduino applications inside the module
for Arduino IDE is just ZIP installation form PlatformIO sources

**Comment by Wiz-IO** [comment]
about MQTT
https://www.youtube.com/watch?v=T0Nt-NJTIaY

**Comment by Wiz-IO** [comment]
PlatformIO - Arduino - Quectel BG96
https://github.com/Wiz-IO/platform-quectel/wiki/Framework-ThreadX#arduino-applications

**Comment by Humancell** [comment]
Hello!  I had a great call with Quectel today, and am moving to begin testing on a BG96 and BC66.

In our conversation I pointed them to your work, and indicated that they needed to officially support your work.  :-)

They knew Radu that you mentioned on your page, and were intrigued at what you have been creating.  This is excellent work, and I told them they need to officially sponsor your work!

I'm waiting on my hardware now for testing.
